apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etl-app
  namespace: integration
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: etl-app
    creationPolicy: Owner
  data:
  - secretKey: db_password
    remoteRef:
      key: integration/etl-app
      property: db_password
