{{- $seen := dict }}
{{- range .Values.pods }}
{{- if not (hasKey $seen .secretName) }}
{{- $_ := set $seen .secretName true }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .secretName }}
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: {{ .vaultKey | quote }}
        property: secret_key
{{- end }}
{{- end }}

